plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/simonsanthosh/Downloads/Others/The Terah Group/Commerce Agents/Projects/Budget Proposals/Grassroot Foundation"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]